language: node_js
branches:
  except:
  - gh-pages
sudo: false
before_script:
  - npm install web-component-tester
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
env:
  global:
    - secure: "iCvXEUobETvgVDewg8u7i6IdzlsbbTB6xLeACAfWIv536IwnPtV2v42BwArSVVkXr4qF/+uHFNsxmrtLivraQAMDrsBEAO7PJfYfCFOwyisS2YtW6pKpO5J4gcf0xTabjC6KYs7GQq7eHzdxxrg45TDMVcfPAsvgA7KiHQtLDjwWBp31qnNkAAhKqDAI8yj1P5DOJT2SWfGfhiPEGmwyT5t0tRrNkGJuFG+4zaIloM5/OJ7yGPW/75UMCxqCFib4fMq+LXqxSg353YYuTX9dED2PlbVbySY1KJ/pXPJKMdLetqoh4p6GHdx7sgxQ/6WMzQzRTEW59dIozXmCyTqbMUWYO83mOdxjC9hjkqKeo5A0hx85OSHLyjju0o6eLMat0SbLNGd9pd8dxE6XFiKl3ueoM51guwk2GlXA0Q/LvE0K0RGldOn58g4sjlM5GEAFKHkszdtKTXBjWTXfXVj9jw00+uLnCThLNUlZJnFCgi9XfNHsuIJyTupoiViF94AhsmFDERS7tX7A18t1zLA+IfT+1a3XXFnYlWT2vD4zrettwJPWQGrFOTU8NmLmWC4Cmm8HM/3aHq64sRyO4hCuaukVheVFxsHiM+IFJhcYV4p9SACjkFN/mnYEp+45luNjs7Z8843Pue4N2IPrORnINGiZVhWRrJlxgh91iJzYCmw="
    - secure: "iglbpJ+GKb6VdELKCIa60Zt9yfMYUTgsjlj/ZmBfrSuoRR/qNx7rmDzs5BmBvCDW10i8TZ14hDxfmhmfDmlWauzUOLdIVJYQizMcWUfElKd8tkPK/yMyJL5v2gs8DU/CFI0Mm4BGSFbG3/i5YVDBWO47H2vf7jSe1vKsEZlbKaK6RZakpZ+rkGJ/mfersTIv9Xcv2aA0MqDuOOtL6L+eNMEosuSmi7thzpkmWhv8yCgm7aQDO9G6yWwHZXx0eKdh9zWAv9omGK37AaeCBd34NPFGrAuOHhXLY9ICPioDzym2yqj/BzytCN/OE3XbcRlfD6Fzax9eLs5zoF41BUMVLYDnqLyhFPrY/NcKl8v/MyjATWSfMp5dFFGY72DLZLLDH95ElpqzMCT3Q3SsiKv/pzqg8MQONDB893mUAza5Zh4YiOLsXikRvImj2o80HEqowiXZ29r1aQCd3GFtGuV2EsqQ+QKPq/kakUdDNEk7c819lIAifpfSpVkkp2XFT54pv2NCGihkr0HRR/a4Ay1p9gtse0uq7viOrjd6AWJX8xvoBaF9mzc4B8ISpPhPeK2hVwkfHJ09G7n3kDlqEBuHyrezRc1DVj6U3ygp7RugXbYE/XE/WCuiaOahqv6jHXgKs8qyiW2OMrhou/r62yoaKGP2Njx7Vd9DexoOVog4HeU="
    - CXX=g++-4.8
node_js:
  - "4"
  - "5"
  - "6"
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
  sauce_connect: true
script:
  - if [ "${TRAVIS_NODE_VERSION}" == "4" ]; then xvfb-run wct; fi
  - istanbul cover ./node_modules/mocha/bin/_mocha test/test.js --report lcov -- -R spec
  - lcov-result-merger 'coverage*/lcov.info' | ./node_modules/coveralls/bin/coveralls.js
